Practical-01: Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas.

Step1: Import the pandas library

In [1]:
#import pandas for the dataset
import pandas as pd

Step2: Create Dataset

In [ ]:
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Rahul","Priya","Amit","Riya","Karan","Krishna","Harry"],
    "Age": [20, 21, 19, 20, 22, 24, 28],
    "City": ["Surat", "Navsari", "Bharuch", "Gandhinagar", "ahemdabad", "Mumbai", "Surat"],
    "Marks": [85, 32, 78, 88, 81, 84, 90]
}

Step3: Covert the dataset into pandas dataframe

In [ ]:
#convert the directory into a pandas Dataframe
df=pd.DataFrame(data)

#dislay the dataset
df

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     32
2  103     Amit   19      Bharuch     78
3  104     Riya   20  Gandhinagar     88
4  105    Karan   22    ahemdabad     81
5  106  Krishna   24       Mumbai     84
6  107    Harry   28        Surat     90

Step4: Save file as CSV file

In [ ]:
#save the dataframe as a CSV file
df.to_csv("students.csv", index=False)

#display confirmation message.
print("Excel file created successfully.")

Excel file created successfully.

Step5: Save File as JSON File

In [ ]:
#save the dataframe as a JSON file
df.to_json("students.json",orient ="records",indent=4)

#display confirmation message.
print("json file created successfully.")

json file created successfully.

Step6: Read the CSV file

In [ ]:
#read the csv file into a new dataframe
df_csv = pd.read_csv("students.csv")

#display the contents of the new dataframe
df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     32
2  103     Amit   19      Bharuch     78
3  104     Riya   20  Gandhinagar     88
4  105    Karan   22    ahemdabad     81
5  106  Krishna   24       Mumbai     84
6  107    Harry   28        Surat     90

Step7: Read the JSON file

In [ ]:
#read the json file into a new dataframe
df_json = pd.read_json("students.json")

#display the contents of the new dataframe
df_json

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     32
2  103     Amit   19      Bharuch     78
3  104     Riya   20  Gandhinagar     88
4  105    Karan   22    ahemdabad     81
5  106  Krishna   24       Mumbai     84
6  107    Harry   28        Surat     90

Step8: Display the first five rows of Dataset

In [ ]:
#display the first five rows  of the dataset

df_csv.head()

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     32
2  103   Amit   19      Bharuch     78
3  104   Riya   20  Gandhinagar     88
4  105  Karan   22    ahemdabad     81

Step9: Display the last five rows

In [ ]:
#display the Last five rows of the dataset

df_csv.tail()

    ID     Name  Age         City  Marks
2  103     Amit   19      Bharuch     78
3  104     Riya   20  Gandhinagar     88
4  105    Karan   22    ahemdabad     81
5  106  Krishna   24       Mumbai     84
6  107    Harry   28        Surat     90

Step:10 Get the Information of the dataset

In [ ]:
#Display information about the dataframe

df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Step:11 Display Statistics for numerical columns

In [ ]:
#Display descriptive statistics for numerical columns

df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  76.857143
std      2.160247   3.109126  20.186039
min    101.000000  19.000000  32.000000
25%    102.500000  20.000000  79.500000
50%    104.000000  21.000000  84.000000
75%    105.500000  23.000000  86.500000
max    107.000000  28.000000  90.000000

Step12: Display the rows and columns (number)

In [ ]:
#Display the number of rows and columns

df_csv.shape

(7, 5)

Step:13 Show the all names in the dataset

In [ ]:
#Display all columns names

df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step14: Show the Datatypes in the Dataset

In [ ]:
#Display the data type of each column

df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

Step15: Show the missing values in the columns

In [ ]:
#Count for the missing value in each column

df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

Step:16 Show the Marks column only

In [ ]:
#Display only the 'Marks' column

df_csv["Marks"]

0    85
1    32
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

Step17: Show only the columns of (Name) and (Marks)

In [ ]:
#Display only the 'Name' and 'Marks' colums

df_csv[["Name","Marks"]]

      Name  Marks
0    Rahul     85
1    Priya     32
2     Amit     78
3     Riya     88
4    Karan     81
5  Krishna     84
6    Harry     90

Step18: Display the marks of the student greater than 80

In [ ]:
#Display students whose marks are greater than 80

df_csv[df_csv["Marks"]>80]

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
3  104     Riya   20  Gandhinagar     88
4  105    Karan   22    ahemdabad     81
5  106  Krishna   24       Mumbai     84
6  107    Harry   28        Surat     90

Step:19 Take the average of the Student Marks column

In [ ]:
#Calculate the average of the 'Marks' column

df_csv["Marks"].mean()

np.float64(76.85714285714286)

Step:20 Display the dataset in descending order (Marks)

In [ ]:
#Sort the dataset in descending order of marks

df_csv.sort_values(by="Marks",ascending=False)

    ID     Name  Age         City  Marks
6  107    Harry   28        Surat     90
3  104     Riya   20  Gandhinagar     88
0  101    Rahul   20        Surat     85
5  106  Krishna   24       Mumbai     84
4  105    Karan   22    ahemdabad     81
2  103     Amit   19      Bharuch     78
1  102    Priya   21      Navsari     32

Step:21 Display the Dataset

In [ ]:
#Display the dataset

df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     32
2  103     Amit   19      Bharuch     78
3  104     Riya   20  Gandhinagar     88
4  105    Karan   22    ahemdabad     81
5  106  Krishna   24       Mumbai     84
6  107    Harry   28        Surat     90