Practical-2 Perform data inspection, cleaning, handling missing values duplicate removal, and data transformation using pandas

Step1: Import the pandas

In [32]:
#import pandas library and assign it the alias 'pd'

import pandas as pd

Step:2 Create the data set

In [33]:
#Create the Dataset of the Students
data = {
    "ID": [101, 102, 103, 104, 104, 105, 106, 107],
    "Name": ["Rahul","Priya","Amit", None, "Riya", "Ajay", "Naresh", "Jenil"],
    "Age": [20, 21, None, 20, 20, 22, 23, 28],
    "City": ["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahemdabad"],
    "Marks": [85, None, 78, 88, 88, 81, 90, 93]
}

Step:3 Display the dataset

In [34]:
#Display the data into dataframe

df=pd.DataFrame(data)

df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

Step 4: Display the First five rows of the Dataset

In [35]:
#Display the first five rows of dataset

df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

Step 5: Display the Last five rows of the Dataset

In [36]:
#Display the last five rows of dataset

df.tail()

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

Step 6: Display the Information of the dataset

In [37]:
#Display detailed information of dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

Step 7: Display statistical info for numerical values

In [38]:
#Generate statistical information for numerical colunms

df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

Step 8: Display the no. of rows and columns

In [39]:
#Display the dimensions of dataset
#output format: (no. of rows, no. of columns)

df.shape

(8, 5)

Step 9: Display the Datatypes of columns

In [40]:
#Display the datatypes of each column

df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

Step 10: Display the names of the each column

In [41]:
#Display the names of all columns in dataframe

df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 11: Check missing values for df

In [42]:
#Check missing values

df.isnull()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

Step 12: Show total numbers value of each columns

In [43]:
#Display total number of all values in each column
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

Step 13: Show the sum of all null values

In [44]:
#Display the sum of all null values

df.isnull().sum().sum()

np.int64(3)

Step 14: Fill the Missing values

In [45]:
#Replace the missing values in the marks column
#fillna() replaces missing values

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

Step 15: Replace the missing values in age column

In [46]:
#Replace missing values in the age column
#Using the average of all students

df["Age"] = df["Age"].fillna(df["Age"].mean())

df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

Step 16: Replace the missing value of names as unknown

In [47]:
#Replace missing names with the text "Unknown"

df["Name"] = df["Name"].fillna("Unknown")

df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 17: Detect the duplicate records

In [48]:
#Check whether each row is duplicated

df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

Step 18: Count the duplicate rows

In [49]:
#Count the total number of duplicate rows

df.duplicated().sum()

np.int64(0)

Step 19: Remove the duplicates records

In [50]:
#Remove the duplicates from dataset

df.drop_duplicates()

df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 20: Rename a column

In [51]:
#Rename the column marks to score

df.rename(columns={"Marks":"Score"}, inplace=True)

df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 21: change the datatype

In [52]:
#Convert the Age column from float to integer

df["Age"] = df["Age"].astype(int)

df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

Step 22: Create the new columns

In [53]:
#Create the new column named as "Final Score"
df["Final_Score"] = df["Score"] + 5

df

    ID     Name  Age       City      Score  Final_Score
0  101    Rahul   20      Surat  85.000000    90.000000
1  102    Priya   21    Navsari  86.142857    91.142857
2  103     Amit   22      Surat  78.000000    83.000000
3  104  Unknown   20    Bharuch  88.000000    93.000000
4  104     Riya   20    Bharuch  88.000000    93.000000
5  105     Ajay   22    Navsari  81.000000    86.000000
6  106   Naresh   23      Surat  90.000000    95.000000
7  107    Jenil   28  Ahemdabad  93.000000    98.000000

Step 23: Convert the Letters to Uppercase

In [54]:
#Convert the text to uppercase ("Name")
df["Name"] = df["Name"].str.upper()

df

    ID     Name  Age       City      Score  Final_Score
0  101    RAHUL   20      Surat  85.000000    90.000000
1  102    PRIYA   21    Navsari  86.142857    91.142857
2  103     AMIT   22      Surat  78.000000    83.000000
3  104  UNKNOWN   20    Bharuch  88.000000    93.000000
4  104     RIYA   20    Bharuch  88.000000    93.000000
5  105     AJAY   22    Navsari  81.000000    86.000000
6  106   NARESH   23      Surat  90.000000    95.000000
7  107    JENIL   28  Ahemdabad  93.000000    98.000000

Step 24:Convert the Letter to Lowercase

In [55]:
#Convert the text to lowercase ("City")
df["City"] = df["City"].str.lower()

df

    ID     Name  Age       City      Score  Final_Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step 25: Remove the Extra Space from the "City"

In [56]:
#Removing the Extra Spcae from "City"
df["City"] = df["City"].str.strip()

df

    ID     Name  Age       City      Score  Final_Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step 26: Sort the Dataset of Final Score column

In [57]:
#Sort the Dataset of Final_Score
df.sort_values(by=["Final_Score"])

df

    ID     Name  Age       City      Score  Final_Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step 27: Save the Updated Dataset

In [58]:
#Save the updated Dataset
df.to_csv('Cleaned_student.csv, index=False')

df

    ID     Name  Age       City      Score  Final_Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000